#!/usr/bin/env bash
# ============================================================================
# viewAIble Userspace Setup — runs without root
#
#   curl -fsSL https://yourdomain.app/setup.sh | bash -s -- TOKEN [PORT]
#
# Installs to ~/.viewaible/. Safe to re-run. No Docker required.
# Installs: ttyd, Node.js (if missing), Claude Code CLI, token proxy
# ============================================================================
set -euo pipefail

TOKEN="${1:?Usage: curl -fsSL https://yourdomain.app/setup.sh | bash -s -- TOKEN [PORT]}"
PORT="${2:-7681}"
DIR="$HOME/.viewaible"
TTYD_PORT=17681

COLS=$(tput cols 2>/dev/null || echo 60)
HR=$(printf '%*s' "$COLS" '' | tr ' ' '─')

echo ""
echo "$HR"
echo "  viewAIble Userspace Setup"
echo "$HR"
echo ""

# ── Validate token is hex ────────────────────────────────────────────────
if ! echo "$TOKEN" | grep -qE '^[0-9a-fA-F]{16,}$'; then
    echo "ERROR: Invalid token. Use the token generated by viewAIble."
    exit 1
fi

# ── Detect architecture ──────────────────────────────────────────────────
ARCH=$(uname -m)
case "$ARCH" in
    x86_64)  TTYD_ARCH="x86_64"; NODE_ARCH="x64" ;;
    aarch64) TTYD_ARCH="aarch64"; NODE_ARCH="arm64" ;;
    *)
        echo "ERROR: Unsupported architecture: $ARCH"
        echo "Supported: x86_64, aarch64 (ARM64)"
        exit 1
        ;;
esac

# ── Stop existing install ────────────────────────────────────────────────
if [ -x "$DIR/stop.sh" ]; then
    echo "[0/4] Stopping existing install..."
    "$DIR/stop.sh" 2>/dev/null || true
fi

# ── Create directory structure ───────────────────────────────────────────
mkdir -p "$DIR"/{bin,logs,pids}

# ── 1. Download ttyd ─────────────────────────────────────────────────────
echo "[1/4] ttyd..."
curl -fsSL -o "$DIR/bin/ttyd" \
    "https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.${TTYD_ARCH}"
chmod +x "$DIR/bin/ttyd"
echo "  $($DIR/bin/ttyd --version 2>&1 | head -1 || echo 'installed')"

# ── 2. Node.js ───────────────────────────────────────────────────────────
echo "[2/4] Node.js..."
if command -v node &>/dev/null && node -v | grep -qE '^v(1[89]|2[0-9])'; then
    NODE_BIN=$(command -v node)
    echo "  $(node -v) (system)"
else
    NODE_VER="v22.12.0"
    echo "  Downloading Node.js $NODE_VER..."
    curl -fsSL "https://nodejs.org/dist/${NODE_VER}/node-${NODE_VER}-linux-${NODE_ARCH}.tar.xz" \
        | tar xJ -C "$DIR"
    rm -rf "$DIR/node"
    mv "$DIR/node-${NODE_VER}-linux-${NODE_ARCH}" "$DIR/node"
    NODE_BIN="$DIR/node/bin/node"
    export PATH="$DIR/node/bin:$PATH"
    echo "  $(node -v) (local)"
fi

# ── 3. Claude Code CLI ──────────────────────────────────────────────────
echo "[3/4] Claude Code CLI..."
# Install to local prefix to avoid permission issues
npm install --prefix "$DIR/npm" -g @anthropic-ai/claude-code >/dev/null 2>&1 || true
export PATH="$DIR/npm/bin:$PATH"
echo "  $(claude --version 2>/dev/null || echo 'installed')"

# ── 4. Configure proxy + services ───────────────────────────────────────
echo "[4/4] Configuring..."

# Token proxy — validates X-Viewaible-Token before forwarding to ttyd
cat > "$DIR/proxy.js" << 'PROXYEOF'
const http = require('http');
const net = require('net');

const TOKEN = process.env.VIEWAIBLE_TOKEN;
const TTYD_PORT = parseInt(process.env.TTYD_PORT || '17681', 10);
const PORT = parseInt(process.env.PORT || '7681', 10);

const server = http.createServer((req, res) => {
    if (req.headers['x-viewaible-token'] !== TOKEN) {
        res.writeHead(403, { 'Content-Type': 'text/plain' });
        return res.end('Forbidden');
    }

    const headers = Object.assign({}, req.headers);
    delete headers['x-viewaible-token'];

    const proxyReq = http.request({
        hostname: '127.0.0.1',
        port: TTYD_PORT,
        path: req.url,
        method: req.method,
        headers: headers,
    }, (proxyRes) => {
        res.writeHead(proxyRes.statusCode, proxyRes.headers);
        proxyRes.pipe(res);
    });

    proxyReq.on('error', () => {
        res.writeHead(502, { 'Content-Type': 'text/plain' });
        res.end('Bad Gateway');
    });

    req.pipe(proxyReq);
});

server.on('upgrade', (req, socket, head) => {
    if (req.headers['x-viewaible-token'] !== TOKEN) {
        socket.write('HTTP/1.1 403 Forbidden\r\n\r\n');
        socket.destroy();
        return;
    }

    const conn = net.connect(TTYD_PORT, '127.0.0.1', () => {
        const hdrs = Object.entries(req.headers)
            .filter(([k]) => k.toLowerCase() !== 'x-viewaible-token')
            .map(([k, v]) => k + ': ' + v)
            .join('\r\n');
        conn.write(req.method + ' ' + req.url + ' HTTP/' + req.httpVersion + '\r\n' + hdrs + '\r\n\r\n');
        if (head.length > 0) conn.write(head);
        socket.pipe(conn);
        conn.pipe(socket);
    });

    conn.on('error', () => {
        socket.write('HTTP/1.1 502 Bad Gateway\r\n\r\n');
        socket.destroy();
    });
    socket.on('error', () => conn.destroy());
});

server.listen(PORT, '0.0.0.0', () => {
    console.log('viewaible proxy :' + PORT + ' -> ttyd :' + TTYD_PORT);
});
PROXYEOF

# Onboarding config for Claude
mkdir -p "$HOME/.claude"
echo '{"hasCompletedOnboarding":true}' > "$HOME/.claude.json"

# Start script
cat > "$DIR/start.sh" << STARTEOF
#!/usr/bin/env bash
DIR="\$(cd "\$(dirname "\$0")" && pwd)"
export PATH="\$DIR/bin:\$DIR/node/bin:\$DIR/npm/bin:\$PATH"

# Stop any existing processes
"\$DIR/stop.sh" 2>/dev/null || true

mkdir -p "\$DIR/logs" "\$DIR/pids"

# ttyd on localhost only — proxy is the only public entrypoint
nohup "\$DIR/bin/ttyd" \\
    --port $TTYD_PORT \\
    --interface 127.0.0.1 \\
    --writable \\
    --terminal-type xterm-256color \\
    --client-option fontSize=13 \\
    --client-option fontFamily='JetBrains Mono,Fira Code,Consolas,monospace' \\
    bash -c 'claude; exec bash' > "\$DIR/logs/ttyd.log" 2>&1 &
echo \$! > "\$DIR/pids/ttyd.pid"

sleep 1

# Token-validating proxy on public port
VIEWAIBLE_TOKEN="$TOKEN" TTYD_PORT=$TTYD_PORT PORT=$PORT \\
    nohup node "\$DIR/proxy.js" > "\$DIR/logs/proxy.log" 2>&1 &
echo \$! > "\$DIR/pids/proxy.pid"

sleep 1

# Verify
TTYD_OK="no"; PROXY_OK="no"
kill -0 \$(cat "\$DIR/pids/ttyd.pid" 2>/dev/null) 2>/dev/null && TTYD_OK="yes"
kill -0 \$(cat "\$DIR/pids/proxy.pid" 2>/dev/null) 2>/dev/null && PROXY_OK="yes"
echo "  ttyd:  \$TTYD_OK"
echo "  proxy: \$PROXY_OK"
STARTEOF
chmod +x "$DIR/start.sh"

# Stop script
cat > "$DIR/stop.sh" << 'STOPEOF'
#!/usr/bin/env bash
DIR="$(cd "$(dirname "$0")" && pwd)"
for f in "$DIR/pids/"*.pid; do
    [ -f "$f" ] && kill "$(cat "$f")" 2>/dev/null; rm -f "$f"
done
STOPEOF
chmod +x "$DIR/stop.sh"

# Auto-start on reboot via crontab
(crontab -l 2>/dev/null | grep -v '\.viewaible/start\.sh' || true; echo "@reboot $DIR/start.sh") | crontab -

# Ensure PATH is set for future logins (idempotent)
MARKER="# viewaible PATH"
if ! grep -qF "$MARKER" "$HOME/.bashrc" 2>/dev/null; then
    echo "" >> "$HOME/.bashrc"
    echo "$MARKER" >> "$HOME/.bashrc"
    echo "export PATH=\"$DIR/bin:$DIR/node/bin:$DIR/npm/bin:\$PATH\"" >> "$HOME/.bashrc"
fi

# ── Start services ───────────────────────────────────────────────────────
echo ""
"$DIR/start.sh"

# ── Done ─────────────────────────────────────────────────────────────────
VPS_IP=$(curl -s4 ifconfig.me 2>/dev/null || echo "unknown")
VPS_IP6=$(curl -s6 ifconfig.me 2>/dev/null || echo "")

echo ""
echo "$HR"
echo "  viewAIble Ready"
echo "$HR"
echo ""
echo "  IPv4:  $VPS_IP"
if [ -n "$VPS_IP6" ] && [ "$VPS_IP6" != "" ]; then
echo "  IPv6:  $VPS_IP6"
fi
echo "  Port:  $PORT"
echo ""
echo "  Go back to viewAIble — it will auto-connect."
echo "  Then run /login in the terminal to authenticate Claude."
echo ""
echo "  Manage:"
echo "    ~/.viewaible/stop.sh   — stop services"
echo "    ~/.viewaible/start.sh  — start services"
echo ""
echo "$HR"
